name: Auto-fix Markdown code blocks

permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  fix-md-code-blocks:
    runs-on: ubuntu-latest
    steps:
      - uses: mahenzon/md-code-block-auto-lang@v1
        with:
          language: python
